// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADL5evG4mb4BVQUnn-8mqmLM6kt3wQiz0',
    appId: '1:119455973043:web:4b180ae4a9045959267ac6',
    messagingSenderId: '119455973043',
    projectId: 'productive-new-version',
    authDomain: 'productive-new-version.firebaseapp.com',
    storageBucket: 'productive-new-version.appspot.com',
    measurementId: 'G-8GPGP8Y4MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0LdAfmkCvCrtSU1FAyO5TbbYNvQpFFDs',
    appId: '1:119455973043:android:2b8b18318cc76158267ac6',
    messagingSenderId: '119455973043',
    projectId: 'productive-new-version',
    storageBucket: 'productive-new-version.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJcGhc3jErhpaYiDQt1Y_3Bepgxh6nTg',
    appId: '1:119455973043:ios:5b661a286f71361f267ac6',
    messagingSenderId: '119455973043',
    projectId: 'productive-new-version',
    storageBucket: 'productive-new-version.appspot.com',
    iosBundleId: 'com.example.productiveNewVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAJcGhc3jErhpaYiDQt1Y_3Bepgxh6nTg',
    appId: '1:119455973043:ios:c83dddf31b64f3b6267ac6',
    messagingSenderId: '119455973043',
    projectId: 'productive-new-version',
    storageBucket: 'productive-new-version.appspot.com',
    iosBundleId: 'com.example.productiveNewVersion.RunnerTests',
  );
}
